import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Icons } from "@/components/icons";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function DashboardPage() {
  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold font-headline md:text-4xl">Dashboard</h1>
        <p className="text-muted-foreground">Your daily progress at a glance.</p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Calories</CardTitle>
            <Icons.Calories className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">1,250 / 2,000 kcal</div>
            <p className="text-xs text-muted-foreground">+200 from last day</p>
            <Progress value={62.5} className="mt-4" />
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Water Intake</CardTitle>
            <Icons.Water className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">1.5 / 2 L</div>
            <p className="text-xs text-muted-foreground">8 glasses consumed</p>
            <Progress value={75} className="mt-4" />
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Weight</CardTitle>
            <Icons.Weight className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">75.2 kg</div>
            <p className="text-xs text-muted-foreground">Target: 70 kg</p>
             <div className="mt-4 h-2.5 rounded-full bg-secondary" />
          </CardContent>
        </Card>
      </div>
      
      <div className="grid gap-6 md:grid-cols-2">
        <Card className="flex flex-col">
            <CardHeader>
                <CardTitle className="font-headline flex items-center gap-2"><Icons.Workout className="text-primary"/> AI Workout Plan</CardTitle>
                <CardDescription>Get a personalized workout plan generated by our AI to reach your goals faster.</CardDescription>
            </CardHeader>
            <CardContent className="flex-grow flex items-end">
                <Link href="/dashboard/workout-generator" className="w-full">
                    <Button className="w-full">Generate Workout</Button>
                </Link>
            </CardContent>
        </Card>
         <Card className="flex flex-col">
            <CardHeader>
                <CardTitle className="font-headline flex items-center gap-2"><Icons.Diet className="text-primary"/> AI Diet Plan</CardTitle>
                <CardDescription>Optimize your nutrition with an AI-generated diet plan tailored to your needs.</CardDescription>
            </CardHeader>
            <CardContent className="flex-grow flex items-end">
                <Link href="/dashboard/diet-generator" className="w-full">
                    <Button className="w-full">Generate Diet</Button>
                </Link>
            </CardContent>
        </Card>
      </div>

       <Card className="border-dashed">
        <CardHeader className="text-center">
          <CardTitle className="font-headline">Advertisement</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex h-32 items-center justify-center rounded-lg bg-muted">
            <p className="text-muted-foreground">Ad placeholder for free users</p>
          </div>
        </CardContent>
      </Card>

    </div>
  );
}
